### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by wesbos** [wesbos/advanced-react-rerecord#18]
Stick with Enzyme? Or move to react-testing-library? 

Any opinions?

**Comment by Asjas** [comment]
`React-Testing-Library` from me :+1:

**Comment by hedgecox** [comment]
Might be a little controversial but I’d be pretty interested in seeing some testing with Cypress

**Comment by bogoroh** [comment]
Enzyme would be awesome!

**Comment by wesbos** [comment]
Thumbs up this for Jest + Enzyme

**Comment by wesbos** [comment]
Thumbs up this for React Testing Library

**Comment by wesbos** [comment]
Thumbs up this for Cypress

**Comment by mathewmorris** [comment]
Soooo, I use Cypress strictly for e2e testing even though the library does allow you to do integration and unit tests. THEN, for Unit/Integration I will use Jest + react-testing-library. That's my take :) I voted accordingly 😄

**Comment by rrackiewicz** [comment]
We use a combination of Jest for unit testing, React Testing Library for component testing, and Cypress for end-to-end testing. We run all of our tests using GitLabs CICD.

**Comment by Asjas** [comment]
@mathewmorris I voted for both RTL and Cypress for the same reason 😄

**Comment by wesbos** [comment]
I would love to but the course would be 100 years long. Maybe a dedicated course on testing in the future could cover all of that

**Comment by SeeStephSay** [comment]
We are learning react-testing-library at Lambda School, so on one hand, I can always use more practice, but on the other, I have never used Enzyme, so it might be nice to try that out?

**Comment by Fotiman** [comment]
> I would love to but the course would be 100 years long. Maybe a dedicated course on testing in the future could cover all of that

I would love to see this, where you test the same project, swapping out the different testing frameworks to see how you would test in each.

**Comment by jbstewart** [comment]
React Testing Library

**Comment by wesbos** [comment]
Jest + react-testing-library it is. 

Most of the test should port over pretty smoothly. Keeping snapshots as they are really helpful in some usecases

**Comment by wesbos** [comment]
testing is finished, now back to the Apollo issues. Hopefully they are fixed!
