### ISSUE TITLE
Apollo 3 isn't launched yet

### ISSUE THREAD

**Issue by wesbos** [wesbos/advanced-react-rerecord#28]
I don't mind recording in Beta, but I'm not sure the API is 100% finished yet. This is the biggest blocker

**Comment by jeltehomminga** [comment]
Looking forward to this course. I wouldn't mind taking the course knowing Apollo 3 is still in Beta and things could still change. If that would become an option

**Comment by voloszad** [comment]
Second that, I would expect updated docs anyway.

**Comment by ludicast** [comment]
Agree with your waiting. If the interface changes that would be the #1 complaint people have.

**Comment by wesbos** [comment]
Not gonna do it - I’ve been burned way too many times with changing APIs when things looks super stable. Causes way too many road blocks for learners and endless support on my end. Sorry folks - I hope soon!

**Comment by lqze** [comment]
@wesbos Thanks for sticking to your guns regarding that, you remain my favourite Canadian. 🍁

**Comment by tusharshuklaa** [comment]
Hi @wesbos, is this the only blocker that is stopping the re-recorded version's release?

**Comment by Asjas** [comment]
@tusharshuklaa Yes, the stable release of [Apollo Client v3.0.0](https://github.com/apollographql/apollo-client/releases) is the blocker Wes is waiting for before he records the update to the course. 🙂

**Comment by dennis-ji** [comment]
keystone.js will be introduced to this course?

**Comment by Asjas** [comment]
Yes Keystone.js will be used for the backend. You can check the backend folder of the repository 🙂

**Comment by dennis-ji** [comment]
So Prisma will not be used in this project, right?

Two questions:
1. why keystone, why not others like [strapi](https://github.com/strapi/strapi)?
2. what's the stack for frontend and backend in the finished work?

Thanks.

**Comment by Asjas** [comment]
>what's the stack for frontend and backend in the finished work?

@dennis-ji You can check the `package.json` files in both the frontend and backend to see the npm packages that is used for the backend and frontend. 🙂
https://github.com/wesbos/advanced-react-rerecord

**Comment by wesbos** [comment]
Going to start recording soon :)

**Comment by SanderGeraedts** [comment]
@wesbos excuse my ignorance in the subject and I know you must get this question way too often, but do you have a ballpark estimate on a release date? If not, do you have a mailing list with updates?

**Comment by rhiannonmonks** [comment]
Can you let us know the main changes Apollo 3 will have to this tutorial overall. And also why you will not use Prisma? I ask because it helps me make decisions for our tech stack, knowing the reasons for and against things

**Comment by wesbos** [comment]
Date: once it's ready OR soon™. I realize this answer is frustrating - will update you once I start recording and as I'm recording

Prisma - I've opted not to use Prisma as their Prisma 2 isn't totally ready yet. I am using Keystone.js as it comes a little bit more "batteries included".  The custom resolvers moved over almost 1:1 so it's really not all that different other than we don't need to handle Auth ourselves and there is a really slick Admin UI that comes with it.

**Comment by petartzar80** [comment]
I apologize if I'm missing something obvious, but if I buy the course now, will I have the access to the updated version too when it arrives? Also, when the updated version does arrive, will there still be access to the ye olde course as well? Thx!

**Comment by vsimonovski** [comment]
> if I buy the course now, will I have the access to the updated version too when it arrives

@petartzar80 Yes.

**Comment by Asjas** [comment]
@petartzar80 Updates to the courses are always free 🙂

You won't have access to the old version of the course when the update launches.

**Comment by petartzar80** [comment]
@vsimonovski @Asjas Thank you guys!

**Comment by rhiannonmonks** [comment]
I would happily pay again. I figure Wes has to do the work all over again and we learn something new. It's really generous that he also offers the new version of the course as part of the same cost as the original, given the content is different. I am looking forward to do the new course. It would be great if perhaps with the actual practical part of the course (ie the coding itself) that we have some videos that explain itself what the differences are of Apollo 3 v 2 and also even a bit more about how Apollo works itself. I found in the last course the 20 min video, where he says to get a beer and relax, and explained GraphQL quite handy, in addition to just implementing it. Between Yoga / Apollo / Heroku / now.sh and Prisma - there's a lot of servers to understand and hence having it outlined the difference of each, the role of each and how they relate to the project / what they do, is to me very helpful, in the same way I really liked how he mapped out each thing in the course overview from front end to back end. Just a suggestion....maybe it's obvious to everyone else and I'm just in server purgatory!

**Comment by smokiebacon** [comment]
I bought this course back in 2018 and was just going to start it, and wondered if this is outdated. Glad to hear recording is on going on! Eagerly waiting! You rock Wes! I listen to Syntax (Wes Bos's podcast) every so often.

**Comment by claym** [comment]
Yep, let's do this thing!

**Comment by wesbos** [comment]
Choo choo

**Comment by rhiannonmonks** [comment]
Any chance you could do this version with AWS Amplify for React / Node.js and GraphQL?!

**Comment by chocobuckle** [comment]
So, considering this ticket was closed 10 weeks ago I'm just curious when you expect to release the new edition of the Advanced React course? It was my understanding that details of the Apollo 3 API were the last remaining roadblock, no? :)

**Comment by Asjas** [comment]
Wes is recording the update to the Advanced React course after he releases his Gatsby Course. He just tweeted that he finished recording the Gatsby Course and still has to edit the videos and create the Gatsby Course Marketing site. Once that is done he'll record the update to this course 🙂
