### ISSUE TITLE
Replace getInitialProps with getStaticProps or getServerSideProps

### ISSUE THREAD

**Issue by zorzysty** [wesbos/advanced-react-rerecord#40]
In those two files: [_document.js](https://github.com/wesbos/advanced-react-rerecord/blob/master/frontend/pages/_document.js) and [_app.js](https://github.com/wesbos/advanced-react-rerecord/blob/master/frontend/pages/_app.js) you're using `getInitialProps` method. Since version 9.3 Next.js [docs](https://nextjs.org/docs/api-reference/data-fetching/getInitialProps) recommend using `getStaticProps` or `getServerSideProps` instead:

> If you're using Next.js 9.3 or newer, we recommend that you use getStaticProps or getServerSideProps instead of getInitialProps.
> 
> These new data fetching methods allow you to have a granular choice between static generation and server-side rendering.

**Comment by alvaaz** [comment]
https://github.com/zeit/next.js/discussions/10946

**Comment by wesbos** [comment]
Doesn’t look like next-with-Apollo works with this. I tried it with no success
