### ISSUE TITLE
Recording in Keystone.js 5 or Prisma 2?

### ISSUE THREAD

**Issue by Riseley** [wesbos/advanced-react-rerecord#43]
Hi, I am going through your Syntax podcast on Keystone again. In the podcast you mentioned that you haven't start recording (blocked by Apollo Client 3 until last week anyway), and you so you haven't decide which to record. You said that it is most probably be Keystone.js (because you ported them in 6 December) but you haven't **_really_** decide.

Now that Apollo Client 3 is finally out + Prisma 2.0 is out (not sure if it is a good or bad timing), which one will you record then? And why?

I know there are much work poured into Keystone but is Keystone 5 really the tech stack that will last for years and benefit many people over Prisma 2?

Personally I am okay with both, but I would like to hear your opinion on this.

I never used Keystone.js 5 so I am not sure whether if it is good or not. But I have a very neutral (lots of love but also lots of hate) relationship with Prisma so yeah, just wanna know why for curiosity.

**Comment by wesbos** [comment]
Hey! Yes sticking with Keystone. I really like that it has a nice admin UI and accounts baked in.

**Comment by Riseley** [comment]
Cool! Excited to watch the rerecords.

**Comment by TilakMaddy** [comment]
soooo may I ask when is the new version of the course gonna be released if you don't mind ?
