### ISSUE TITLE
Use next.js Api or stick with GraphQL Yoga

### ISSUE THREAD

**Issue by mm-parthy** [wesbos/advanced-react-rerecord#47]
Hey @wesbos ,
since next.js has the possibility to implement Apis, would you port all the logic from Yoga to the Api?

**Comment by Asjas** [comment]
@mm-parthy Wes is planning on using Keystone.js for the backend so most of the `graphql-yoga` logic that existed in the previous recording will be implemented in Keystone. 🙂

That is unless Wes decides to not use Keystone.js anymore but there has been no mention to drop it 🙂

**Comment by Satsh24** [comment]
Any timeline/date when this course be released ?

**Comment by Asjas** [comment]
Soon™, Wes will record the update to the course after he releases his Gatsby course 🙂

**Comment by thdatnguyen** [comment]
Nice to hear that!!!!

**Comment by j4jefferson** [comment]
Prisma2 is looking pretty exciting! Just throwing it out there. I built my startup with prisma and graphql. Wes' course convinced me it was a great stack and I think it's just getting better. I had a lot of issues figuring out how to deploy Prisma on GCP Kubernetes Engine, but it works nice.
