### ISSUE TITLE
Hi Wes, any idea how long until the rerecord will be released?

### ISSUE THREAD

**Issue by osintops** [wesbos/advanced-react-rerecord#71]
Just a quick check in, I purchased the original course and have been waiting for the updated version. I have checked back in from time to time and see the rerecord is still listed but haven't heard any news for quite sometime. 

Any release dates for the new improved advanced react course?

Bests,

Sean

**Comment by silicakes** [comment]
This should shed some light in things:
https://github.com/wesbos/advanced-react-rerecord/issues/55#issuecomment-713797779

**Comment by wesbos** [comment]
soon :)

**Comment by wesbos** [comment]
I am recording right now, Just FYI!

**Comment by osintops** [comment]
@wesbos I can't begin to tell you how excited I am, thanks for sharing the update here I am sure its been asked a thousand times. This is off topic a little but nodejs tutorial using Golang would be amazing (would love to have your style of project based teaching building out APIs with Go). Just throwing it out there as your are the more adventurous kinda teacher that pushes the boundaries ;)
