### ISSUE TITLE
Hosting:

### ISSUE THREAD

**Issue by wesbos** [wesbos/advanced-react-rerecord#8]
Digital Ocean with pm2 and Nginx
Heroku

Not sure if Zeit Now will work as they can't really host node apps

**Comment by mckernanin** [comment]
Curious as to why you said now "can't really host node apps"? What issues have you had?

**Comment by alvaaz** [comment]
I try with Heroku and had a good result

**Comment by wesbos** [comment]
apparently it is possible on now! https://github.com/mitchellhamilton/keystonejs-now-example

**Comment by wesbos** [comment]
Heroku for sure will work :)

**Comment by alvaaz** [comment]
Heroku works but you have to make some settings:

```
const keystone = new Keystone({
  ....
  secureCookies: false
});
```

**Comment by mckernanin** [comment]
Ah ok specifically keystone + node, not node in general. 👍

**Comment by wesbos** [comment]
Well in my experience I haven't had a node app that just works on Now 2. all of them require you to change how the app is written

**Comment by Oluwasetemi** [comment]
Having digital ocean for both the frontend and backend using nginx and pm2 will be so dope

**Comment by ashhitch** [comment]
DigitalOcean with pm2 and Nginx or maybe Caddy?

**Comment by wesbos** [comment]
Yeah def digital ocean + nginx + pm2. It's what I use on most of my apps and i love it.

**Comment by GPorter43** [comment]
Are you still going to demonstrate hosting the front and back end on a single droplet/instance?
If not would you be able to add that to another course or YouTube video?

**Comment by wesbos** [comment]
Yep - it will all be on a single droplet :)

**Comment by fdiaz7** [comment]
Digital Ocean with pm2 and Nginx

**Comment by rhiannonmonks** [comment]
Can anyone explain why Now 2 does not work with node  easily (both from a theoretical and practical standpoint?) When you say, it requires to change how the app is written, I would like to better understand this? Thanks!

**Comment by bezvoshchuk** [comment]
Is AWS an option?

**Comment by leafyshark** [comment]
Hey Wes, I currently have an app up and running using what I learnt from you. It uses Prisma, Docker, MongoDB, etc and is hosted on the cheapest DigitalOcean droplet using nginx and pm2 - it works perfectly! https://flamboyant-pasteur-5ec451.netlify.app/

**Comment by cjschamith** [comment]
why this is taking so long..:( 
I'm waiting for the update to buy advancedreact course.
I check this repo almost every day but still, this hosting issue isn't resolved yet.
I think you already completed recordings except for this hosting one.   
Take as much time you want for the module 10. Please add the rest of the modules.

Thank you,
I really appreciate your work.
you're really a very good instructor.

**Comment by Asjas** [comment]
@cjschamith Wes is busy finishing his Gatsby course recording before he starts recording this course update. 🙂

The hosting isn't an issue, Wes already chose Digital Ocean 😄

**Comment by wesbos** [comment]
thanks everyone! I know this should have been out sooner, but many of these items are out of my control. Will be recorded right after my gatsby course. Thanks for your patience :)
