### ISSUE TITLE
Loading queries with Webpack

### ISSUE THREAD

**Issue by estrada9166** [wesbos/advanced-react-rerecord#9]
Feel free to close this issue - just sharing some cool stuff that can be used.

[Loading queries with Webpack](https://www.apollographql.com/docs/react/integrations/webpack/)
 
That way `.graphql` files can be imported in the js file and will be already parsed with `gql`

`next.config.js`
```js
module.exports = {
  webpack: (config, options) => {
    config.module.rules.push({
      test: /\.(graphql|gql)$/,
      exclude: /node_modules/,
      loader: "graphql-tag/loader"
    });

    return config;
  }
};
```

**Comment by wesbos** [comment]
thanks - I'm aware of this but I like to put the queries inside the components themselves so I don't need this : )
