### ISSUE TITLE
Unhandled Runtime Error Error: useKeystone must be called inside a KeystoneProvider component

### ISSUE THREAD

**Issue by toticavalcanti** [wesbos/advanced-react-rerecord#93]
Hi wes,
I try run your code, but when I try to access one particular user, or products, or roles, etc. Or try add some product... in the admin cmd, I receive this message: useKeystone must be called inside a KeystoneProvider component.
How fix this issue?
I can list all the users, products, etc without problem.
Thank you
\o/

**Comment by Asjas** [comment]
Hi, Are you using the code from the `advanced-react-rerecord` repo or the `advanced-react` repo? 🙂

**Comment by toticavalcanti** [comment]
I tried both :), but the error in **advanced-react** is another:
� There was an error initialising Keystone
Error: Expected a Boolean, Object, or Function for User.access.read, but got undefined
Expected a Boolean, Object, or Function for User.access.update, but got undefined

This error occurs with all schemas.

**Comment by toticavalcanti** [comment]
I run yarn again in advanced-react, and all works fine. thank you :)
